//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonSite.Web.Admin.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://utrust.zzbz.net/", ConfigurationName="ServiceReference1.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 user_account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/userlogin", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.userloginResponse userlogin(BonSite.Web.Admin.ServiceReference1.userloginRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 appid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getuserinfo", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getuserinfoResponse getuserinfo(BonSite.Web.Admin.ServiceReference1.getuserinfoRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 appid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getaccesstoken", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getaccesstokenResponse getaccesstoken(BonSite.Web.Admin.ServiceReference1.getaccesstokenRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getclasslist", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getclasslistResponse getclasslist(BonSite.Web.Admin.ServiceReference1.getclasslistRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getdepartmentlist", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getdepartmentlistResponse getdepartmentlist(BonSite.Web.Admin.ServiceReference1.getdepartmentlistRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getuserlist", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getuserlistResponse getuserlist(BonSite.Web.Admin.ServiceReference1.getuserlistRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getschoolyearlist", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getschoolyearlistResponse getschoolyearlist(BonSite.Web.Admin.ServiceReference1.getschoolyearlistRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getcourselist", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getcourselistResponse getcourselist(BonSite.Web.Admin.ServiceReference1.getcourselistRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getcanlendarlistbymonth", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthResponse getcanlendarlistbymonth(BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getcanlendardatebymonth", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthResponse getcanlendardatebymonth(BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getcanlendarlistbydate", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateResponse getcanlendarlistbydate(BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/getcanlendardetail", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.getcanlendardetailResponse getcanlendardetail(BonSite.Web.Admin.ServiceReference1.getcanlendardetailRequest request);
        
        // CODEGEN: 命名空间 http://utrust.zzbz.net/ 的元素名称 access_token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://utrust.zzbz.net/addwxconfirm", ReplyAction="*")]
        BonSite.Web.Admin.ServiceReference1.addwxconfirmResponse addwxconfirm(BonSite.Web.Admin.ServiceReference1.addwxconfirmRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userloginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userlogin", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.userloginRequestBody Body;
        
        public userloginRequest() {
        }
        
        public userloginRequest(BonSite.Web.Admin.ServiceReference1.userloginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class userloginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user_pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string isaccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string appid;
        
        public userloginRequestBody() {
        }
        
        public userloginRequestBody(string user_account, string user_pwd, string isaccount, string appid) {
            this.user_account = user_account;
            this.user_pwd = user_pwd;
            this.isaccount = isaccount;
            this.appid = appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userloginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userloginResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.userloginResponseBody Body;
        
        public userloginResponse() {
        }
        
        public userloginResponse(BonSite.Web.Admin.ServiceReference1.userloginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class userloginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userloginResult;
        
        public userloginResponseBody() {
        }
        
        public userloginResponseBody(string userloginResult) {
            this.userloginResult = userloginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getuserinfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getuserinfo", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getuserinfoRequestBody Body;
        
        public getuserinfoRequest() {
        }
        
        public getuserinfoRequest(BonSite.Web.Admin.ServiceReference1.getuserinfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getuserinfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user_token;
        
        public getuserinfoRequestBody() {
        }
        
        public getuserinfoRequestBody(string appid, string user_token) {
            this.appid = appid;
            this.user_token = user_token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getuserinfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getuserinfoResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getuserinfoResponseBody Body;
        
        public getuserinfoResponse() {
        }
        
        public getuserinfoResponse(BonSite.Web.Admin.ServiceReference1.getuserinfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getuserinfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getuserinfoResult;
        
        public getuserinfoResponseBody() {
        }
        
        public getuserinfoResponseBody(string getuserinfoResult) {
            this.getuserinfoResult = getuserinfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getaccesstokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getaccesstoken", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getaccesstokenRequestBody Body;
        
        public getaccesstokenRequest() {
        }
        
        public getaccesstokenRequest(BonSite.Web.Admin.ServiceReference1.getaccesstokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getaccesstokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string secret;
        
        public getaccesstokenRequestBody() {
        }
        
        public getaccesstokenRequestBody(string appid, string secret) {
            this.appid = appid;
            this.secret = secret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getaccesstokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getaccesstokenResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getaccesstokenResponseBody Body;
        
        public getaccesstokenResponse() {
        }
        
        public getaccesstokenResponse(BonSite.Web.Admin.ServiceReference1.getaccesstokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getaccesstokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getaccesstokenResult;
        
        public getaccesstokenResponseBody() {
        }
        
        public getaccesstokenResponseBody(string getaccesstokenResult) {
            this.getaccesstokenResult = getaccesstokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getclasslistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getclasslist", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getclasslistRequestBody Body;
        
        public getclasslistRequest() {
        }
        
        public getclasslistRequest(BonSite.Web.Admin.ServiceReference1.getclasslistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getclasslistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string school_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pagenow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pagesize;
        
        public getclasslistRequestBody() {
        }
        
        public getclasslistRequestBody(string access_token, string school_code, int pagenow, int pagesize) {
            this.access_token = access_token;
            this.school_code = school_code;
            this.pagenow = pagenow;
            this.pagesize = pagesize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getclasslistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getclasslistResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getclasslistResponseBody Body;
        
        public getclasslistResponse() {
        }
        
        public getclasslistResponse(BonSite.Web.Admin.ServiceReference1.getclasslistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getclasslistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getclasslistResult;
        
        public getclasslistResponseBody() {
        }
        
        public getclasslistResponseBody(string getclasslistResult) {
            this.getclasslistResult = getclasslistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getdepartmentlistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getdepartmentlist", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getdepartmentlistRequestBody Body;
        
        public getdepartmentlistRequest() {
        }
        
        public getdepartmentlistRequest(BonSite.Web.Admin.ServiceReference1.getdepartmentlistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getdepartmentlistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string school_code;
        
        public getdepartmentlistRequestBody() {
        }
        
        public getdepartmentlistRequestBody(string access_token, string school_code) {
            this.access_token = access_token;
            this.school_code = school_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getdepartmentlistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getdepartmentlistResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getdepartmentlistResponseBody Body;
        
        public getdepartmentlistResponse() {
        }
        
        public getdepartmentlistResponse(BonSite.Web.Admin.ServiceReference1.getdepartmentlistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getdepartmentlistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getdepartmentlistResult;
        
        public getdepartmentlistResponseBody() {
        }
        
        public getdepartmentlistResponseBody(string getdepartmentlistResult) {
            this.getdepartmentlistResult = getdepartmentlistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getuserlistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getuserlist", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getuserlistRequestBody Body;
        
        public getuserlistRequest() {
        }
        
        public getuserlistRequest(BonSite.Web.Admin.ServiceReference1.getuserlistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getuserlistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string school_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string role_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string updatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pagenow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pagesize;
        
        public getuserlistRequestBody() {
        }
        
        public getuserlistRequestBody(string access_token, string school_code, string role_code, string updatetime, int pagenow, int pagesize) {
            this.access_token = access_token;
            this.school_code = school_code;
            this.role_code = role_code;
            this.updatetime = updatetime;
            this.pagenow = pagenow;
            this.pagesize = pagesize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getuserlistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getuserlistResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getuserlistResponseBody Body;
        
        public getuserlistResponse() {
        }
        
        public getuserlistResponse(BonSite.Web.Admin.ServiceReference1.getuserlistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getuserlistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getuserlistResult;
        
        public getuserlistResponseBody() {
        }
        
        public getuserlistResponseBody(string getuserlistResult) {
            this.getuserlistResult = getuserlistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getschoolyearlistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getschoolyearlist", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getschoolyearlistRequestBody Body;
        
        public getschoolyearlistRequest() {
        }
        
        public getschoolyearlistRequest(BonSite.Web.Admin.ServiceReference1.getschoolyearlistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getschoolyearlistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string school_code;
        
        public getschoolyearlistRequestBody() {
        }
        
        public getschoolyearlistRequestBody(string access_token, string school_code) {
            this.access_token = access_token;
            this.school_code = school_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getschoolyearlistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getschoolyearlistResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getschoolyearlistResponseBody Body;
        
        public getschoolyearlistResponse() {
        }
        
        public getschoolyearlistResponse(BonSite.Web.Admin.ServiceReference1.getschoolyearlistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getschoolyearlistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getschoolyearlistResult;
        
        public getschoolyearlistResponseBody() {
        }
        
        public getschoolyearlistResponseBody(string getschoolyearlistResult) {
            this.getschoolyearlistResult = getschoolyearlistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcourselistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcourselist", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcourselistRequestBody Body;
        
        public getcourselistRequest() {
        }
        
        public getcourselistRequest(BonSite.Web.Admin.ServiceReference1.getcourselistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcourselistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string school_code;
        
        public getcourselistRequestBody() {
        }
        
        public getcourselistRequestBody(string access_token, string school_code) {
            this.access_token = access_token;
            this.school_code = school_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcourselistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcourselistResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcourselistResponseBody Body;
        
        public getcourselistResponse() {
        }
        
        public getcourselistResponse(BonSite.Web.Admin.ServiceReference1.getcourselistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcourselistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getcourselistResult;
        
        public getcourselistResponseBody() {
        }
        
        public getcourselistResponseBody(string getcourselistResult) {
            this.getcourselistResult = getcourselistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcanlendarlistbymonthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcanlendarlistbymonth", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthRequestBody Body;
        
        public getcanlendarlistbymonthRequest() {
        }
        
        public getcanlendarlistbymonthRequest(BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcanlendarlistbymonthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string school_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string month;
        
        public getcanlendarlistbymonthRequestBody() {
        }
        
        public getcanlendarlistbymonthRequestBody(string access_token, string school_code, string month) {
            this.access_token = access_token;
            this.school_code = school_code;
            this.month = month;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcanlendarlistbymonthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcanlendarlistbymonthResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthResponseBody Body;
        
        public getcanlendarlistbymonthResponse() {
        }
        
        public getcanlendarlistbymonthResponse(BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcanlendarlistbymonthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getcanlendarlistbymonthResult;
        
        public getcanlendarlistbymonthResponseBody() {
        }
        
        public getcanlendarlistbymonthResponseBody(string getcanlendarlistbymonthResult) {
            this.getcanlendarlistbymonthResult = getcanlendarlistbymonthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcanlendardatebymonthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcanlendardatebymonth", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthRequestBody Body;
        
        public getcanlendardatebymonthRequest() {
        }
        
        public getcanlendardatebymonthRequest(BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcanlendardatebymonthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string school_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string month;
        
        public getcanlendardatebymonthRequestBody() {
        }
        
        public getcanlendardatebymonthRequestBody(string access_token, string school_code, string month) {
            this.access_token = access_token;
            this.school_code = school_code;
            this.month = month;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcanlendardatebymonthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcanlendardatebymonthResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthResponseBody Body;
        
        public getcanlendardatebymonthResponse() {
        }
        
        public getcanlendardatebymonthResponse(BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcanlendardatebymonthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getcanlendardatebymonthResult;
        
        public getcanlendardatebymonthResponseBody() {
        }
        
        public getcanlendardatebymonthResponseBody(string getcanlendardatebymonthResult) {
            this.getcanlendardatebymonthResult = getcanlendardatebymonthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcanlendarlistbydateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcanlendarlistbydate", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateRequestBody Body;
        
        public getcanlendarlistbydateRequest() {
        }
        
        public getcanlendarlistbydateRequest(BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcanlendarlistbydateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string school_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ca_begaintime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ca_endtime;
        
        public getcanlendarlistbydateRequestBody() {
        }
        
        public getcanlendarlistbydateRequestBody(string access_token, string school_code, string ca_begaintime, string ca_endtime) {
            this.access_token = access_token;
            this.school_code = school_code;
            this.ca_begaintime = ca_begaintime;
            this.ca_endtime = ca_endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcanlendarlistbydateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcanlendarlistbydateResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateResponseBody Body;
        
        public getcanlendarlistbydateResponse() {
        }
        
        public getcanlendarlistbydateResponse(BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcanlendarlistbydateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getcanlendarlistbydateResult;
        
        public getcanlendarlistbydateResponseBody() {
        }
        
        public getcanlendarlistbydateResponseBody(string getcanlendarlistbydateResult) {
            this.getcanlendarlistbydateResult = getcanlendarlistbydateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcanlendardetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcanlendardetail", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcanlendardetailRequestBody Body;
        
        public getcanlendardetailRequest() {
        }
        
        public getcanlendardetailRequest(BonSite.Web.Admin.ServiceReference1.getcanlendardetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcanlendardetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ca_id;
        
        public getcanlendardetailRequestBody() {
        }
        
        public getcanlendardetailRequestBody(string access_token, int ca_id) {
            this.access_token = access_token;
            this.ca_id = ca_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcanlendardetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcanlendardetailResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.getcanlendardetailResponseBody Body;
        
        public getcanlendardetailResponse() {
        }
        
        public getcanlendardetailResponse(BonSite.Web.Admin.ServiceReference1.getcanlendardetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class getcanlendardetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getcanlendardetailResult;
        
        public getcanlendardetailResponseBody() {
        }
        
        public getcanlendardetailResponseBody(string getcanlendardetailResult) {
            this.getcanlendardetailResult = getcanlendardetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addwxconfirmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addwxconfirm", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.addwxconfirmRequestBody Body;
        
        public addwxconfirmRequest() {
        }
        
        public addwxconfirmRequest(BonSite.Web.Admin.ServiceReference1.addwxconfirmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class addwxconfirmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string access_token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mob;
        
        public addwxconfirmRequestBody() {
        }
        
        public addwxconfirmRequestBody(string access_token, string oid, string mob) {
            this.access_token = access_token;
            this.oid = oid;
            this.mob = mob;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addwxconfirmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addwxconfirmResponse", Namespace="http://utrust.zzbz.net/", Order=0)]
        public BonSite.Web.Admin.ServiceReference1.addwxconfirmResponseBody Body;
        
        public addwxconfirmResponse() {
        }
        
        public addwxconfirmResponse(BonSite.Web.Admin.ServiceReference1.addwxconfirmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://utrust.zzbz.net/")]
    public partial class addwxconfirmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addwxconfirmResult;
        
        public addwxconfirmResponseBody() {
        }
        
        public addwxconfirmResponseBody(string addwxconfirmResult) {
            this.addwxconfirmResult = addwxconfirmResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : BonSite.Web.Admin.ServiceReference1.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<BonSite.Web.Admin.ServiceReference1.UserServiceSoap>, BonSite.Web.Admin.ServiceReference1.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.userloginResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.userlogin(BonSite.Web.Admin.ServiceReference1.userloginRequest request) {
            return base.Channel.userlogin(request);
        }
        
        public string userlogin(string user_account, string user_pwd, string isaccount, string appid) {
            BonSite.Web.Admin.ServiceReference1.userloginRequest inValue = new BonSite.Web.Admin.ServiceReference1.userloginRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.userloginRequestBody();
            inValue.Body.user_account = user_account;
            inValue.Body.user_pwd = user_pwd;
            inValue.Body.isaccount = isaccount;
            inValue.Body.appid = appid;
            BonSite.Web.Admin.ServiceReference1.userloginResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).userlogin(inValue);
            return retVal.Body.userloginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getuserinfoResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getuserinfo(BonSite.Web.Admin.ServiceReference1.getuserinfoRequest request) {
            return base.Channel.getuserinfo(request);
        }
        
        public string getuserinfo(string appid, string user_token) {
            BonSite.Web.Admin.ServiceReference1.getuserinfoRequest inValue = new BonSite.Web.Admin.ServiceReference1.getuserinfoRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getuserinfoRequestBody();
            inValue.Body.appid = appid;
            inValue.Body.user_token = user_token;
            BonSite.Web.Admin.ServiceReference1.getuserinfoResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getuserinfo(inValue);
            return retVal.Body.getuserinfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getaccesstokenResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getaccesstoken(BonSite.Web.Admin.ServiceReference1.getaccesstokenRequest request) {
            return base.Channel.getaccesstoken(request);
        }
        
        public string getaccesstoken(string appid, string secret) {
            BonSite.Web.Admin.ServiceReference1.getaccesstokenRequest inValue = new BonSite.Web.Admin.ServiceReference1.getaccesstokenRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getaccesstokenRequestBody();
            inValue.Body.appid = appid;
            inValue.Body.secret = secret;
            BonSite.Web.Admin.ServiceReference1.getaccesstokenResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getaccesstoken(inValue);
            return retVal.Body.getaccesstokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getclasslistResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getclasslist(BonSite.Web.Admin.ServiceReference1.getclasslistRequest request) {
            return base.Channel.getclasslist(request);
        }
        
        public string getclasslist(string access_token, string school_code, int pagenow, int pagesize) {
            BonSite.Web.Admin.ServiceReference1.getclasslistRequest inValue = new BonSite.Web.Admin.ServiceReference1.getclasslistRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getclasslistRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.school_code = school_code;
            inValue.Body.pagenow = pagenow;
            inValue.Body.pagesize = pagesize;
            BonSite.Web.Admin.ServiceReference1.getclasslistResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getclasslist(inValue);
            return retVal.Body.getclasslistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getdepartmentlistResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getdepartmentlist(BonSite.Web.Admin.ServiceReference1.getdepartmentlistRequest request) {
            return base.Channel.getdepartmentlist(request);
        }
        
        public string getdepartmentlist(string access_token, string school_code) {
            BonSite.Web.Admin.ServiceReference1.getdepartmentlistRequest inValue = new BonSite.Web.Admin.ServiceReference1.getdepartmentlistRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getdepartmentlistRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.school_code = school_code;
            BonSite.Web.Admin.ServiceReference1.getdepartmentlistResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getdepartmentlist(inValue);
            return retVal.Body.getdepartmentlistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getuserlistResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getuserlist(BonSite.Web.Admin.ServiceReference1.getuserlistRequest request) {
            return base.Channel.getuserlist(request);
        }
        
        public string getuserlist(string access_token, string school_code, string role_code, string updatetime, int pagenow, int pagesize) {
            BonSite.Web.Admin.ServiceReference1.getuserlistRequest inValue = new BonSite.Web.Admin.ServiceReference1.getuserlistRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getuserlistRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.school_code = school_code;
            inValue.Body.role_code = role_code;
            inValue.Body.updatetime = updatetime;
            inValue.Body.pagenow = pagenow;
            inValue.Body.pagesize = pagesize;
            BonSite.Web.Admin.ServiceReference1.getuserlistResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getuserlist(inValue);
            return retVal.Body.getuserlistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getschoolyearlistResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getschoolyearlist(BonSite.Web.Admin.ServiceReference1.getschoolyearlistRequest request) {
            return base.Channel.getschoolyearlist(request);
        }
        
        public string getschoolyearlist(string access_token, string school_code) {
            BonSite.Web.Admin.ServiceReference1.getschoolyearlistRequest inValue = new BonSite.Web.Admin.ServiceReference1.getschoolyearlistRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getschoolyearlistRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.school_code = school_code;
            BonSite.Web.Admin.ServiceReference1.getschoolyearlistResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getschoolyearlist(inValue);
            return retVal.Body.getschoolyearlistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getcourselistResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getcourselist(BonSite.Web.Admin.ServiceReference1.getcourselistRequest request) {
            return base.Channel.getcourselist(request);
        }
        
        public string getcourselist(string access_token, string school_code) {
            BonSite.Web.Admin.ServiceReference1.getcourselistRequest inValue = new BonSite.Web.Admin.ServiceReference1.getcourselistRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getcourselistRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.school_code = school_code;
            BonSite.Web.Admin.ServiceReference1.getcourselistResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getcourselist(inValue);
            return retVal.Body.getcourselistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getcanlendarlistbymonth(BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthRequest request) {
            return base.Channel.getcanlendarlistbymonth(request);
        }
        
        public string getcanlendarlistbymonth(string access_token, string school_code, string month) {
            BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthRequest inValue = new BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.school_code = school_code;
            inValue.Body.month = month;
            BonSite.Web.Admin.ServiceReference1.getcanlendarlistbymonthResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getcanlendarlistbymonth(inValue);
            return retVal.Body.getcanlendarlistbymonthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getcanlendardatebymonth(BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthRequest request) {
            return base.Channel.getcanlendardatebymonth(request);
        }
        
        public string getcanlendardatebymonth(string access_token, string school_code, string month) {
            BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthRequest inValue = new BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.school_code = school_code;
            inValue.Body.month = month;
            BonSite.Web.Admin.ServiceReference1.getcanlendardatebymonthResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getcanlendardatebymonth(inValue);
            return retVal.Body.getcanlendardatebymonthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getcanlendarlistbydate(BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateRequest request) {
            return base.Channel.getcanlendarlistbydate(request);
        }
        
        public string getcanlendarlistbydate(string access_token, string school_code, string ca_begaintime, string ca_endtime) {
            BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateRequest inValue = new BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.school_code = school_code;
            inValue.Body.ca_begaintime = ca_begaintime;
            inValue.Body.ca_endtime = ca_endtime;
            BonSite.Web.Admin.ServiceReference1.getcanlendarlistbydateResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getcanlendarlistbydate(inValue);
            return retVal.Body.getcanlendarlistbydateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.getcanlendardetailResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.getcanlendardetail(BonSite.Web.Admin.ServiceReference1.getcanlendardetailRequest request) {
            return base.Channel.getcanlendardetail(request);
        }
        
        public string getcanlendardetail(string access_token, int ca_id) {
            BonSite.Web.Admin.ServiceReference1.getcanlendardetailRequest inValue = new BonSite.Web.Admin.ServiceReference1.getcanlendardetailRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.getcanlendardetailRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.ca_id = ca_id;
            BonSite.Web.Admin.ServiceReference1.getcanlendardetailResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).getcanlendardetail(inValue);
            return retVal.Body.getcanlendardetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BonSite.Web.Admin.ServiceReference1.addwxconfirmResponse BonSite.Web.Admin.ServiceReference1.UserServiceSoap.addwxconfirm(BonSite.Web.Admin.ServiceReference1.addwxconfirmRequest request) {
            return base.Channel.addwxconfirm(request);
        }
        
        public string addwxconfirm(string access_token, string oid, string mob) {
            BonSite.Web.Admin.ServiceReference1.addwxconfirmRequest inValue = new BonSite.Web.Admin.ServiceReference1.addwxconfirmRequest();
            inValue.Body = new BonSite.Web.Admin.ServiceReference1.addwxconfirmRequestBody();
            inValue.Body.access_token = access_token;
            inValue.Body.oid = oid;
            inValue.Body.mob = mob;
            BonSite.Web.Admin.ServiceReference1.addwxconfirmResponse retVal = ((BonSite.Web.Admin.ServiceReference1.UserServiceSoap)(this)).addwxconfirm(inValue);
            return retVal.Body.addwxconfirmResult;
        }
    }
}
