//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonSite.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_users
    {
        public int user_id { get; set; }
        public string user_account { get; set; }
        public string user_pwd { get; set; }
        public string user_salt { get; set; }
        public string user_name { get; set; }
        public Nullable<int> user_sex { get; set; }
        public string user_avatarhost { get; set; }
        public string user_avatar { get; set; }
        public Nullable<int> school_id { get; set; }
        public string class_id { get; set; }
        public string user_mobile { get; set; }
        public string user_email { get; set; }
        public Nullable<int> user_classid { get; set; }
        public string user_position { get; set; }
        public string user_schoolnum { get; set; }
        public string user_role { get; set; }
        public int user_state { get; set; }
        public int user_addtime { get; set; }
        public Nullable<int> user_updatetime { get; set; }
        public Nullable<int> user_birthday { get; set; }
        public Nullable<int> area_provinceid { get; set; }
        public Nullable<int> area_cityid { get; set; }
        public Nullable<int> area_areaid { get; set; }
        public string area_areaname { get; set; }
        public string user_address { get; set; }
        public string user_cordno { get; set; }
        public Nullable<int> user_lastlogintime { get; set; }
        public string user_lastloginip { get; set; }
        public string user_usedname { get; set; }
        public Nullable<int> department_id { get; set; }
        public string school_name { get; set; }
        public string user_nation { get; set; }
        public string user_information { get; set; }
        public string user_specialty { get; set; }
        public string user_blood { get; set; }
        public Nullable<decimal> user_logincs { get; set; }
        public Nullable<decimal> user_onlinetime { get; set; }
        public Nullable<int> user_relateparentid { get; set; }
        public Nullable<int> user_relationship { get; set; }
        public string user_face { get; set; }
    }
}
