//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace BonSite.Web.UserService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserServiceSoap", Namespace="http://utrust.zzbz.net/")]
    public partial class UserService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback userloginOperationCompleted;
        
        private System.Threading.SendOrPostCallback getuserinfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getaccesstokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getclasslistOperationCompleted;
        
        private System.Threading.SendOrPostCallback getdepartmentlistOperationCompleted;
        
        private System.Threading.SendOrPostCallback getuserrolelistOperationCompleted;
        
        private System.Threading.SendOrPostCallback getuserlistOperationCompleted;
        
        private System.Threading.SendOrPostCallback getschoolyearlistOperationCompleted;
        
        private System.Threading.SendOrPostCallback getcourselistOperationCompleted;
        
        private System.Threading.SendOrPostCallback getcanlendarlistbymonthOperationCompleted;
        
        private System.Threading.SendOrPostCallback getcanlendardatebymonthOperationCompleted;
        
        private System.Threading.SendOrPostCallback getcanlendarlistbydateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getcanlendardetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback addwxconfirmOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserService() {
            this.Url = global::BonSite.Web.Properties.Settings.Default.BonSite_Web_UserService_UserService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event userloginCompletedEventHandler userloginCompleted;
        
        /// <remarks/>
        public event getuserinfoCompletedEventHandler getuserinfoCompleted;
        
        /// <remarks/>
        public event getaccesstokenCompletedEventHandler getaccesstokenCompleted;
        
        /// <remarks/>
        public event getclasslistCompletedEventHandler getclasslistCompleted;
        
        /// <remarks/>
        public event getdepartmentlistCompletedEventHandler getdepartmentlistCompleted;
        
        /// <remarks/>
        public event getuserrolelistCompletedEventHandler getuserrolelistCompleted;
        
        /// <remarks/>
        public event getuserlistCompletedEventHandler getuserlistCompleted;
        
        /// <remarks/>
        public event getschoolyearlistCompletedEventHandler getschoolyearlistCompleted;
        
        /// <remarks/>
        public event getcourselistCompletedEventHandler getcourselistCompleted;
        
        /// <remarks/>
        public event getcanlendarlistbymonthCompletedEventHandler getcanlendarlistbymonthCompleted;
        
        /// <remarks/>
        public event getcanlendardatebymonthCompletedEventHandler getcanlendardatebymonthCompleted;
        
        /// <remarks/>
        public event getcanlendarlistbydateCompletedEventHandler getcanlendarlistbydateCompleted;
        
        /// <remarks/>
        public event getcanlendardetailCompletedEventHandler getcanlendardetailCompleted;
        
        /// <remarks/>
        public event addwxconfirmCompletedEventHandler addwxconfirmCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/userlogin", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string userlogin(string user_account, string user_pwd, string isaccount, string appid) {
            object[] results = this.Invoke("userlogin", new object[] {
                        user_account,
                        user_pwd,
                        isaccount,
                        appid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void userloginAsync(string user_account, string user_pwd, string isaccount, string appid) {
            this.userloginAsync(user_account, user_pwd, isaccount, appid, null);
        }
        
        /// <remarks/>
        public void userloginAsync(string user_account, string user_pwd, string isaccount, string appid, object userState) {
            if ((this.userloginOperationCompleted == null)) {
                this.userloginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuserloginOperationCompleted);
            }
            this.InvokeAsync("userlogin", new object[] {
                        user_account,
                        user_pwd,
                        isaccount,
                        appid}, this.userloginOperationCompleted, userState);
        }
        
        private void OnuserloginOperationCompleted(object arg) {
            if ((this.userloginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.userloginCompleted(this, new userloginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getuserinfo", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getuserinfo(string appid, string user_token) {
            object[] results = this.Invoke("getuserinfo", new object[] {
                        appid,
                        user_token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getuserinfoAsync(string appid, string user_token) {
            this.getuserinfoAsync(appid, user_token, null);
        }
        
        /// <remarks/>
        public void getuserinfoAsync(string appid, string user_token, object userState) {
            if ((this.getuserinfoOperationCompleted == null)) {
                this.getuserinfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetuserinfoOperationCompleted);
            }
            this.InvokeAsync("getuserinfo", new object[] {
                        appid,
                        user_token}, this.getuserinfoOperationCompleted, userState);
        }
        
        private void OngetuserinfoOperationCompleted(object arg) {
            if ((this.getuserinfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getuserinfoCompleted(this, new getuserinfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getaccesstoken", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getaccesstoken(string appid, string secret) {
            object[] results = this.Invoke("getaccesstoken", new object[] {
                        appid,
                        secret});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getaccesstokenAsync(string appid, string secret) {
            this.getaccesstokenAsync(appid, secret, null);
        }
        
        /// <remarks/>
        public void getaccesstokenAsync(string appid, string secret, object userState) {
            if ((this.getaccesstokenOperationCompleted == null)) {
                this.getaccesstokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetaccesstokenOperationCompleted);
            }
            this.InvokeAsync("getaccesstoken", new object[] {
                        appid,
                        secret}, this.getaccesstokenOperationCompleted, userState);
        }
        
        private void OngetaccesstokenOperationCompleted(object arg) {
            if ((this.getaccesstokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getaccesstokenCompleted(this, new getaccesstokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getclasslist", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getclasslist(string access_token, string school_code, int pagenow, int pagesize) {
            object[] results = this.Invoke("getclasslist", new object[] {
                        access_token,
                        school_code,
                        pagenow,
                        pagesize});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getclasslistAsync(string access_token, string school_code, int pagenow, int pagesize) {
            this.getclasslistAsync(access_token, school_code, pagenow, pagesize, null);
        }
        
        /// <remarks/>
        public void getclasslistAsync(string access_token, string school_code, int pagenow, int pagesize, object userState) {
            if ((this.getclasslistOperationCompleted == null)) {
                this.getclasslistOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetclasslistOperationCompleted);
            }
            this.InvokeAsync("getclasslist", new object[] {
                        access_token,
                        school_code,
                        pagenow,
                        pagesize}, this.getclasslistOperationCompleted, userState);
        }
        
        private void OngetclasslistOperationCompleted(object arg) {
            if ((this.getclasslistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getclasslistCompleted(this, new getclasslistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getdepartmentlist", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getdepartmentlist(string access_token, string school_code) {
            object[] results = this.Invoke("getdepartmentlist", new object[] {
                        access_token,
                        school_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getdepartmentlistAsync(string access_token, string school_code) {
            this.getdepartmentlistAsync(access_token, school_code, null);
        }
        
        /// <remarks/>
        public void getdepartmentlistAsync(string access_token, string school_code, object userState) {
            if ((this.getdepartmentlistOperationCompleted == null)) {
                this.getdepartmentlistOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetdepartmentlistOperationCompleted);
            }
            this.InvokeAsync("getdepartmentlist", new object[] {
                        access_token,
                        school_code}, this.getdepartmentlistOperationCompleted, userState);
        }
        
        private void OngetdepartmentlistOperationCompleted(object arg) {
            if ((this.getdepartmentlistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getdepartmentlistCompleted(this, new getdepartmentlistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getuserrolelist", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getuserrolelist(string access_token) {
            object[] results = this.Invoke("getuserrolelist", new object[] {
                        access_token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getuserrolelistAsync(string access_token) {
            this.getuserrolelistAsync(access_token, null);
        }
        
        /// <remarks/>
        public void getuserrolelistAsync(string access_token, object userState) {
            if ((this.getuserrolelistOperationCompleted == null)) {
                this.getuserrolelistOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetuserrolelistOperationCompleted);
            }
            this.InvokeAsync("getuserrolelist", new object[] {
                        access_token}, this.getuserrolelistOperationCompleted, userState);
        }
        
        private void OngetuserrolelistOperationCompleted(object arg) {
            if ((this.getuserrolelistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getuserrolelistCompleted(this, new getuserrolelistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getuserlist", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getuserlist(string access_token, string school_code, string role_code, string updatetime, int pagenow, int pagesize) {
            object[] results = this.Invoke("getuserlist", new object[] {
                        access_token,
                        school_code,
                        role_code,
                        updatetime,
                        pagenow,
                        pagesize});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getuserlistAsync(string access_token, string school_code, string role_code, string updatetime, int pagenow, int pagesize) {
            this.getuserlistAsync(access_token, school_code, role_code, updatetime, pagenow, pagesize, null);
        }
        
        /// <remarks/>
        public void getuserlistAsync(string access_token, string school_code, string role_code, string updatetime, int pagenow, int pagesize, object userState) {
            if ((this.getuserlistOperationCompleted == null)) {
                this.getuserlistOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetuserlistOperationCompleted);
            }
            this.InvokeAsync("getuserlist", new object[] {
                        access_token,
                        school_code,
                        role_code,
                        updatetime,
                        pagenow,
                        pagesize}, this.getuserlistOperationCompleted, userState);
        }
        
        private void OngetuserlistOperationCompleted(object arg) {
            if ((this.getuserlistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getuserlistCompleted(this, new getuserlistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getschoolyearlist", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getschoolyearlist(string access_token, string school_code) {
            object[] results = this.Invoke("getschoolyearlist", new object[] {
                        access_token,
                        school_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getschoolyearlistAsync(string access_token, string school_code) {
            this.getschoolyearlistAsync(access_token, school_code, null);
        }
        
        /// <remarks/>
        public void getschoolyearlistAsync(string access_token, string school_code, object userState) {
            if ((this.getschoolyearlistOperationCompleted == null)) {
                this.getschoolyearlistOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetschoolyearlistOperationCompleted);
            }
            this.InvokeAsync("getschoolyearlist", new object[] {
                        access_token,
                        school_code}, this.getschoolyearlistOperationCompleted, userState);
        }
        
        private void OngetschoolyearlistOperationCompleted(object arg) {
            if ((this.getschoolyearlistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getschoolyearlistCompleted(this, new getschoolyearlistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getcourselist", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getcourselist(string access_token, string school_code) {
            object[] results = this.Invoke("getcourselist", new object[] {
                        access_token,
                        school_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getcourselistAsync(string access_token, string school_code) {
            this.getcourselistAsync(access_token, school_code, null);
        }
        
        /// <remarks/>
        public void getcourselistAsync(string access_token, string school_code, object userState) {
            if ((this.getcourselistOperationCompleted == null)) {
                this.getcourselistOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetcourselistOperationCompleted);
            }
            this.InvokeAsync("getcourselist", new object[] {
                        access_token,
                        school_code}, this.getcourselistOperationCompleted, userState);
        }
        
        private void OngetcourselistOperationCompleted(object arg) {
            if ((this.getcourselistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getcourselistCompleted(this, new getcourselistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getcanlendarlistbymonth", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getcanlendarlistbymonth(string access_token, string school_code, string month) {
            object[] results = this.Invoke("getcanlendarlistbymonth", new object[] {
                        access_token,
                        school_code,
                        month});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getcanlendarlistbymonthAsync(string access_token, string school_code, string month) {
            this.getcanlendarlistbymonthAsync(access_token, school_code, month, null);
        }
        
        /// <remarks/>
        public void getcanlendarlistbymonthAsync(string access_token, string school_code, string month, object userState) {
            if ((this.getcanlendarlistbymonthOperationCompleted == null)) {
                this.getcanlendarlistbymonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetcanlendarlistbymonthOperationCompleted);
            }
            this.InvokeAsync("getcanlendarlistbymonth", new object[] {
                        access_token,
                        school_code,
                        month}, this.getcanlendarlistbymonthOperationCompleted, userState);
        }
        
        private void OngetcanlendarlistbymonthOperationCompleted(object arg) {
            if ((this.getcanlendarlistbymonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getcanlendarlistbymonthCompleted(this, new getcanlendarlistbymonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getcanlendardatebymonth", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getcanlendardatebymonth(string access_token, string school_code, string month) {
            object[] results = this.Invoke("getcanlendardatebymonth", new object[] {
                        access_token,
                        school_code,
                        month});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getcanlendardatebymonthAsync(string access_token, string school_code, string month) {
            this.getcanlendardatebymonthAsync(access_token, school_code, month, null);
        }
        
        /// <remarks/>
        public void getcanlendardatebymonthAsync(string access_token, string school_code, string month, object userState) {
            if ((this.getcanlendardatebymonthOperationCompleted == null)) {
                this.getcanlendardatebymonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetcanlendardatebymonthOperationCompleted);
            }
            this.InvokeAsync("getcanlendardatebymonth", new object[] {
                        access_token,
                        school_code,
                        month}, this.getcanlendardatebymonthOperationCompleted, userState);
        }
        
        private void OngetcanlendardatebymonthOperationCompleted(object arg) {
            if ((this.getcanlendardatebymonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getcanlendardatebymonthCompleted(this, new getcanlendardatebymonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getcanlendarlistbydate", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getcanlendarlistbydate(string access_token, string school_code, string ca_begaintime, string ca_endtime) {
            object[] results = this.Invoke("getcanlendarlistbydate", new object[] {
                        access_token,
                        school_code,
                        ca_begaintime,
                        ca_endtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getcanlendarlistbydateAsync(string access_token, string school_code, string ca_begaintime, string ca_endtime) {
            this.getcanlendarlistbydateAsync(access_token, school_code, ca_begaintime, ca_endtime, null);
        }
        
        /// <remarks/>
        public void getcanlendarlistbydateAsync(string access_token, string school_code, string ca_begaintime, string ca_endtime, object userState) {
            if ((this.getcanlendarlistbydateOperationCompleted == null)) {
                this.getcanlendarlistbydateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetcanlendarlistbydateOperationCompleted);
            }
            this.InvokeAsync("getcanlendarlistbydate", new object[] {
                        access_token,
                        school_code,
                        ca_begaintime,
                        ca_endtime}, this.getcanlendarlistbydateOperationCompleted, userState);
        }
        
        private void OngetcanlendarlistbydateOperationCompleted(object arg) {
            if ((this.getcanlendarlistbydateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getcanlendarlistbydateCompleted(this, new getcanlendarlistbydateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/getcanlendardetail", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getcanlendardetail(string access_token, int ca_id) {
            object[] results = this.Invoke("getcanlendardetail", new object[] {
                        access_token,
                        ca_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getcanlendardetailAsync(string access_token, int ca_id) {
            this.getcanlendardetailAsync(access_token, ca_id, null);
        }
        
        /// <remarks/>
        public void getcanlendardetailAsync(string access_token, int ca_id, object userState) {
            if ((this.getcanlendardetailOperationCompleted == null)) {
                this.getcanlendardetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetcanlendardetailOperationCompleted);
            }
            this.InvokeAsync("getcanlendardetail", new object[] {
                        access_token,
                        ca_id}, this.getcanlendardetailOperationCompleted, userState);
        }
        
        private void OngetcanlendardetailOperationCompleted(object arg) {
            if ((this.getcanlendardetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getcanlendardetailCompleted(this, new getcanlendardetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utrust.zzbz.net/addwxconfirm", RequestNamespace="http://utrust.zzbz.net/", ResponseNamespace="http://utrust.zzbz.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string addwxconfirm(string access_token, string oid, string mob) {
            object[] results = this.Invoke("addwxconfirm", new object[] {
                        access_token,
                        oid,
                        mob});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addwxconfirmAsync(string access_token, string oid, string mob) {
            this.addwxconfirmAsync(access_token, oid, mob, null);
        }
        
        /// <remarks/>
        public void addwxconfirmAsync(string access_token, string oid, string mob, object userState) {
            if ((this.addwxconfirmOperationCompleted == null)) {
                this.addwxconfirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddwxconfirmOperationCompleted);
            }
            this.InvokeAsync("addwxconfirm", new object[] {
                        access_token,
                        oid,
                        mob}, this.addwxconfirmOperationCompleted, userState);
        }
        
        private void OnaddwxconfirmOperationCompleted(object arg) {
            if ((this.addwxconfirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addwxconfirmCompleted(this, new addwxconfirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void userloginCompletedEventHandler(object sender, userloginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class userloginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal userloginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getuserinfoCompletedEventHandler(object sender, getuserinfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getuserinfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getuserinfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getaccesstokenCompletedEventHandler(object sender, getaccesstokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getaccesstokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getaccesstokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getclasslistCompletedEventHandler(object sender, getclasslistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getclasslistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getclasslistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getdepartmentlistCompletedEventHandler(object sender, getdepartmentlistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getdepartmentlistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getdepartmentlistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getuserrolelistCompletedEventHandler(object sender, getuserrolelistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getuserrolelistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getuserrolelistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getuserlistCompletedEventHandler(object sender, getuserlistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getuserlistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getuserlistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getschoolyearlistCompletedEventHandler(object sender, getschoolyearlistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getschoolyearlistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getschoolyearlistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getcourselistCompletedEventHandler(object sender, getcourselistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getcourselistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getcourselistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getcanlendarlistbymonthCompletedEventHandler(object sender, getcanlendarlistbymonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getcanlendarlistbymonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getcanlendarlistbymonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getcanlendardatebymonthCompletedEventHandler(object sender, getcanlendardatebymonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getcanlendardatebymonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getcanlendardatebymonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getcanlendarlistbydateCompletedEventHandler(object sender, getcanlendarlistbydateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getcanlendarlistbydateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getcanlendarlistbydateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getcanlendardetailCompletedEventHandler(object sender, getcanlendardetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getcanlendardetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getcanlendardetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void addwxconfirmCompletedEventHandler(object sender, addwxconfirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addwxconfirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addwxconfirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591