//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceContractTest1ClientForm.Service1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service1.IFirstService", CallbackContract=typeof(ServiceContractTest1ClientForm.Service1.IFirstServiceCallback))]
    public interface IFirstService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/GetDataString", ReplyAction="http://tempuri.org/IFirstService/GetDataStringResponse")]
        string GetDataString(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/HelloWorld", ReplyAction="http://tempuri.org/IFirstService/HelloWorldResponse")]
        string HelloWorld(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFirstServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFirstService/NotifyClientMsg")]
        void NotifyClientMsg(string devStateInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFirstServiceChannel : ServiceContractTest1ClientForm.Service1.IFirstService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirstServiceClient : System.ServiceModel.DuplexClientBase<ServiceContractTest1ClientForm.Service1.IFirstService>, ServiceContractTest1ClientForm.Service1.IFirstService {
        
        public FirstServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FirstServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FirstServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FirstServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FirstServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string GetDataString(string name) {
            return base.Channel.GetDataString(name);
        }
        
        public string HelloWorld(string str) {
            return base.Channel.HelloWorld(str);
        }
    }
}
