//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Welding.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>WeldingWorkClothes</string>
  <string>WeldingProtectiveShoes</string>
  <string>LongSleeveLeatherGloves</string>
  <string>HandGeldWeldingMask</string>
  <string>SelfSuctionTypeRespirator</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Utensil1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Utensil1"]));
            }
            set {
                this["Utensil1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>WeldingWorkClothes</string>
  <string>WeldingProtectiveShoes</string>
  <string>LongSleeveLeatherGloves</string>
  <string>HandGeldWeldingMask</string>
  <string>SelfSuctionTypeRespirator</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Utensil2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Utensil2"]));
            }
            set {
                this["Utensil2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>WeldingWorkClothes</string>
  <string>WeldingProtectiveShoes</string>
  <string>ShortSleevedSheepskinGloves</string>
  <string>HeadMountedAutomaticLightChangingFaceMask</string>
  <string>SelfSuctionTypeRespirator</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Utensil3 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Utensil3"]));
            }
            set {
                this["Utensil3"] = value;
            }
        }
    }
}
